name: NekoList
version: 1.1.0
main: hanamuramiyu.pawkin.net.NekoList
description: Advanced whitelist system
author: Hanamura Miyu
api-version: 1.21
commands:
  whitelist:
    description: Manage whitelist
    usage: /whitelist <help|reload|on|off|list|add|remove>
    aliases: [wl]